//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardAbilities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CardAbilities()
        {
            this.Cards_CardsAbilities = new HashSet<Cards_CardsAbilities>();
            this.ManaCost = new HashSet<ManaCost>();
        }
    
        public long CardAbilitiesID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsPassive { get; set; }
        public Nullable<long> Cost { get; set; }
        public string AdditionalCondition { get; set; }
        public Nullable<long> AbilityType { get; set; }
    
        public virtual AbilityTypes AbilityTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cards_CardsAbilities> Cards_CardsAbilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManaCost> ManaCost { get; set; }
    }
}
