//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cards()
        {
            this.Cards1 = new HashSet<Cards>();
            this.Cards_CardsAbilities = new HashSet<Cards_CardsAbilities>();
            this.CardsHasFeatures = new HashSet<CardsHasFeatures>();
            this.CardsToSell = new HashSet<CardsToSell>();
            this.DeckHasCards = new HashSet<DeckHasCards>();
            this.FavouriteCards = new HashSet<FavouriteCards>();
            this.ManaCost = new HashSet<ManaCost>();
            this.ProvidedMana = new HashSet<ProvidedMana>();
        }
    
        public long CardID { get; set; }
        public string Name { get; set; }
        public long Type { get; set; }
        public long Version { get; set; }
        public long ColorAssignment { get; set; }
        public string Hyperlink { get; set; }
        public long TotalManaCost { get; set; }
        public Nullable<long> AttackPower { get; set; }
        public Nullable<long> Health { get; set; }
        public Nullable<long> SecondSideCardID { get; set; }
        public string FableDescription { get; set; }
        public string Footer { get; set; }
        public string Rarity { get; set; }
        public string ReleaseYear { get; set; }
        public string OrderNumberInExpansion { get; set; }
        public Nullable<bool> WantToBuy { get; set; }
        public Nullable<long> SubTypeID { get; set; }
    
        public virtual SubTypes SubTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cards> Cards1 { get; set; }
        public virtual Cards Cards2 { get; set; }
        public virtual ManaType ManaType { get; set; }
        public virtual Versions Versions { get; set; }
        public virtual CardTypes CardTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cards_CardsAbilities> Cards_CardsAbilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardsHasFeatures> CardsHasFeatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardsToSell> CardsToSell { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeckHasCards> DeckHasCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavouriteCards> FavouriteCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManaCost> ManaCost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProvidedMana> ProvidedMana { get; set; }
    }
}
