//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavouriteCards
    {
        public long FavouriteCardID { get; set; }
        public Nullable<long> CardID { get; set; }
    
        public virtual Cards Cards { get; set; }
    }
}
