//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavouriteDecks
    {
        public long FavouriteDeckID { get; set; }
        public long DeckID { get; set; }
    
        public virtual Decks Decks { get; set; }
    }
}
