//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HelpContent
    {
        public long HelpContentID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
    }
}
