//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManaCost
    {
        public long ManaCostID { get; set; }
        public int Amount { get; set; }
        public long ManaID { get; set; }
        public Nullable<long> CardID { get; set; }
        public Nullable<long> AbilityID { get; set; }
    
        public virtual CardAbilities CardAbilities { get; set; }
        public virtual Cards Cards { get; set; }
        public virtual ManaType ManaType { get; set; }
    }
}
