//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvidedMana
    {
        public long ProvidedManaID { get; set; }
        public long Amount { get; set; }
        public string AdditionalNotes { get; set; }
        public long ManaID { get; set; }
        public long CardID { get; set; }
    
        public virtual Cards Cards { get; set; }
        public virtual ManaType ManaType { get; set; }
    }
}
