//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SQLiteDatabase_MagicConnectionString : DbContext
    {
        public SQLiteDatabase_MagicConnectionString()
            : base("name=SQLiteDatabase_MagicConnectionString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AbilityTypes> AbilityTypes { get; set; }
        public virtual DbSet<CardAbilities> CardAbilities { get; set; }
        public virtual DbSet<Cards> Cards { get; set; }
        public virtual DbSet<Cards_CardsAbilities> Cards_CardsAbilities { get; set; }
        public virtual DbSet<CardsHasFeatures> CardsHasFeatures { get; set; }
        public virtual DbSet<CardsToSell> CardsToSell { get; set; }
        public virtual DbSet<CardTypes> CardTypes { get; set; }
        public virtual DbSet<DeckHasCards> DeckHasCards { get; set; }
        public virtual DbSet<Decks> Decks { get; set; }
        public virtual DbSet<FavouriteCards> FavouriteCards { get; set; }
        public virtual DbSet<FavouriteDecks> FavouriteDecks { get; set; }
        public virtual DbSet<Features> Features { get; set; }
        public virtual DbSet<HelpContent> HelpContent { get; set; }
        public virtual DbSet<ManaCost> ManaCost { get; set; }
        public virtual DbSet<ManaType> ManaType { get; set; }
        public virtual DbSet<ProvidedMana> ProvidedMana { get; set; }
        public virtual DbSet<Rules> Rules { get; set; }
        public virtual DbSet<SubTypes> SubTypes { get; set; }
        public virtual DbSet<Versions> Versions { get; set; }
    }
}
